<script lang="ts">
  export let width: number = 100;
  export let height: number = 100;
</script>

<div>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="{width}px"
    height="{height}px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    data-darkreader-inline-bgimage=""
    data-darkreader-inline-bgcolor=""
  >
    <circle
      cx="50"
      cy="50"
      r="32"
      stroke-width="8"
      stroke="var(--accent-color)"
      stroke-dasharray="50.26548245743669 50.26548245743669"
      fill="none"
      stroke-linecap="round"
      data-darkreader-inline-stroke=""
      style="--darkreader-inline-stroke:#e2616a;"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        dur="1s"
        repeatCount="indefinite"
        keyTimes="0;1"
        values="0 50 50;360 50 50"
      />
    </circle>
    <circle
      cx="50"
      cy="50"
      r="23"
      stroke-width="8"
      stroke="var(--tertiary-color)"
      stroke-dasharray="36.12831551628262 36.12831551628262"
      stroke-dashoffset="36.12831551628262"
      fill="none"
      stroke-linecap="round"
      data-darkreader-inline-stroke=""
      style="--darkreader-inline-stroke:#f8b066;"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        dur="1s"
        repeatCount="indefinite"
        keyTimes="0;1"
        values="0 50 50;-360 50 50"
      />
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</div>

<style>
  div {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vmin;
  }

  svg {
    margin: auto;
    background: none;
    display: block;
    --darkreader-inline-bgimage: initial;
    --darkreader-inline-bgcolor: #181a1b;
    shape-rendering: auto;
  }
</style>
